package com.shuto.mam.sis.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.shuto.mam.sis.obft.formulaservice.ObjectFactory;

/**
 * This class was generated by Apache CXF 2.7.15
 * 2015-03-26T19:41:40.268+08:00
 * Generated source version: 2.7.15
 * 
 */
/**
 * 
com.shuto.mam.sis.service.FormulaService 江苏
* @author       zhaowei  zhaowei@shuoto.cn
* @date         2017年5月16日 下午5:45:26
* @Copyright:   2017 Shuto版权所有
* @version      V1.0
 */
@WebService(targetNamespace = "http://service.sis.mam.shuto.com/", name = "FormulaService")
@XmlSeeAlso({ObjectFactory.class})
public interface FormulaService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getByFormula", targetNamespace = "http://service.sis.mam.shuto.com/", className = "com.shuto.mam.sis.obft.formulaservice.GetByFormula")
    @WebMethod
    @ResponseWrapper(localName = "getByFormulaResponse", targetNamespace = "http://service.sis.mam.shuto.com/", className = "com.shuto.mam.sis.obft.formulaservice.GetByFormulaResponse")
    public java.lang.String getByFormula(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
