package com.shuto.mam.app.cron.ws;

import java.math.BigDecimal;
import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name="RcjlmxWebService", targetNamespace="http://service.batchacceptance.business.crp.com/")
@XmlSeeAlso({ObjectFactory.class})
public abstract interface RcjlmxWebService
{
  @WebMethod
  @WebResult(targetNamespace="")
  @RequestWrapper(localName="addRcjlmx", targetNamespace="http://service.batchacceptance.business.crp.com/", className="com.shuto.mam.app.cron.ws.AddRcjlmx")
  @ResponseWrapper(localName="addRcjlmxResponse", targetNamespace="http://service.batchacceptance.business.crp.com/", className="com.shuto.mam.app.cron.ws.AddRcjlmxResponse")
  public abstract List<String> addRcjlmx(@WebParam(name="psw", targetNamespace="") String paramString1, @WebParam(name="oRgId", targetNamespace="") Long paramLong1, @WebParam(name="oRgSub", targetNamespace="") String paramString2, @WebParam(name="rOleId", targetNamespace="") Long paramLong2, @WebParam(name="lEgalOrgId", targetNamespace="") Long paramLong3, @WebParam(name="jLType", targetNamespace="") Long paramLong4, @WebParam(name="jLDt2", targetNamespace="") XMLGregorianCalendar paramXMLGregorianCalendar, @WebParam(name="jLSd", targetNamespace="") BigDecimal paramBigDecimal1, @WebParam(name="jLXh", targetNamespace="") Long paramLong5, @WebParam(name="jLCch", targetNamespace="") String paramString3, @WebParam(name="jLFzm", targetNamespace="") String paramString4, @WebParam(name="jLGys", targetNamespace="") String paramString5, @WebParam(name="jLHwm", targetNamespace="") String paramString6, @WebParam(name="jLShf", targetNamespace="") String paramString7, @WebParam(name="jLCx", targetNamespace="") String paramString8, @WebParam(name="qTyMzFh", targetNamespace="") BigDecimal paramBigDecimal2, @WebParam(name="qTyZzFh", targetNamespace="") BigDecimal paramBigDecimal3, @WebParam(name="qTyJzFh", targetNamespace="") BigDecimal paramBigDecimal4, @WebParam(name="qTyPz", targetNamespace="") BigDecimal paramBigDecimal5, @WebParam(name="qTyMz", targetNamespace="") BigDecimal paramBigDecimal6, @WebParam(name="qTyZz", targetNamespace="") BigDecimal paramBigDecimal7, @WebParam(name="qTyJz", targetNamespace="") BigDecimal paramBigDecimal8, @WebParam(name="jLJlr", targetNamespace="") String paramString9, @WebParam(name="jLNote", targetNamespace="") String paramString10, @WebParam(name="jLId", targetNamespace="") String paramString11, @WebParam(name="rEfId", targetNamespace="") String paramString12, @WebParam(name="ySjlQltKq", targetNamespace="") BigDecimal paramBigDecimal9, @WebParam(name="ySjlQltKs", targetNamespace="") BigDecimal paramBigDecimal10, @WebParam(name="jLTimes", targetNamespace="") String paramString13, @WebParam(name="sPecType", targetNamespace="") String paramString14);

  @WebMethod(action="addRcjlmx2")
  @WebResult(targetNamespace="")
  @RequestWrapper(localName="addRcjlmx2", targetNamespace="http://service.batchacceptance.business.crp.com/", className="com.shuto.mam.app.cron.ws.AddRcjlmx2")
  @ResponseWrapper(localName="addRcjlmx2Response", targetNamespace="http://service.batchacceptance.business.crp.com/", className="com.shuto.mam.app.cron.ws.AddRcjlmx2Response")
  public abstract List<String> addRcjlmx2(@WebParam(name="psw", targetNamespace="") String paramString1, @WebParam(name="oRgId", targetNamespace="") Long paramLong1, @WebParam(name="oRgSub", targetNamespace="") String paramString2, @WebParam(name="rOleId", targetNamespace="") Long paramLong2, @WebParam(name="lEgalOrgId", targetNamespace="") Long paramLong3, @WebParam(name="jLType", targetNamespace="") Long paramLong4, @WebParam(name="jLDt2", targetNamespace="") XMLGregorianCalendar paramXMLGregorianCalendar1, @WebParam(name="jLSd", targetNamespace="") BigDecimal paramBigDecimal1, @WebParam(name="jLXh", targetNamespace="") Long paramLong5, @WebParam(name="jLCch", targetNamespace="") String paramString3, @WebParam(name="jLFzm", targetNamespace="") String paramString4, @WebParam(name="jLGys", targetNamespace="") String paramString5, @WebParam(name="jLHwm", targetNamespace="") String paramString6, @WebParam(name="jLShf", targetNamespace="") String paramString7, @WebParam(name="jLCx", targetNamespace="") String paramString8, @WebParam(name="qTyMzFh", targetNamespace="") BigDecimal paramBigDecimal2, @WebParam(name="qTyZzFh", targetNamespace="") BigDecimal paramBigDecimal3, @WebParam(name="qTyJzFh", targetNamespace="") BigDecimal paramBigDecimal4, @WebParam(name="qTyPz", targetNamespace="") BigDecimal paramBigDecimal5, @WebParam(name="qTyMz", targetNamespace="") BigDecimal paramBigDecimal6, @WebParam(name="qTyZz", targetNamespace="") BigDecimal paramBigDecimal7, @WebParam(name="qTyJz", targetNamespace="") BigDecimal paramBigDecimal8, @WebParam(name="jLJlr", targetNamespace="") String paramString9, @WebParam(name="jLNote", targetNamespace="") String paramString10, @WebParam(name="jLId", targetNamespace="") String paramString11, @WebParam(name="rEfId", targetNamespace="") String paramString12, @WebParam(name="ySjlQltKq", targetNamespace="") BigDecimal paramBigDecimal9, @WebParam(name="ySjlQltKs", targetNamespace="") BigDecimal paramBigDecimal10, @WebParam(name="jLTimes", targetNamespace="") String paramString13, @WebParam(name="sPecType", targetNamespace="") String paramString14, @WebParam(name="uNLoadArea", targetNamespace="") String paramString15, @WebParam(name="vArAttr1", targetNamespace="") String paramString16, @WebParam(name="vArAttr2", targetNamespace="") String paramString17, @WebParam(name="vArAttr3", targetNamespace="") String paramString18, @WebParam(name="vArAttr4", targetNamespace="") String paramString19, @WebParam(name="nUmAttr1", targetNamespace="") BigDecimal paramBigDecimal11, @WebParam(name="nUmAttr2", targetNamespace="") BigDecimal paramBigDecimal12, @WebParam(name="dAteAttr1", targetNamespace="") XMLGregorianCalendar paramXMLGregorianCalendar2, @WebParam(name="dAteAttr2", targetNamespace="") XMLGregorianCalendar paramXMLGregorianCalendar3);
}